# Generated by Django 5.0.1 on 2024-05-19 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saree', '0010_purchaseorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='supplier',
        ),
    ]
