# Generated by Django 5.0.1 on 2024-09-02 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saree', '0013_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='sentiment',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
