# Generated by Django 5.0.1 on 2024-09-20 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saree', '0015_product_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('out_for_delivery', 'Out for Delivery'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('canceled', 'Canceled')], default='processing', max_length=20),
        ),
    ]
